version: '3'
services:
  nginx:
    build:
      dockerfile: ./Dockerfilenginx
      context: .
    image: matheusgadelha2323/nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
    networks:
      - redelocal
    depends_on:
      - "web1"
      - "web2"
      - "web3"
  db:
    build:
      dockerfile: ./Dockerfiledb
      context: .
    image: matheusgadelha2323/db:latest
    container_name: db
    networks:
      - redelocal
    ports:
      - "3306"

  web1:
    build:
      dockerfile: ./Dockerfileweb
      context: .
    image: matheusgadelha2323/web:latest
    container_name: web1
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web2:
    image: matheusgadelha2323/web:latest
    container_name: web2
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"
  web3:
    image: matheusgadelha2323/web:latest
    container_name: web3
    ports:
      - "80"
    networks:
      - redelocal
    depends_on:
      - "db"

networks:
  redelocal:
    driver: bridge
