---
- hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  gather_facts: true
  tasks:
    - name: 'Instalação de pacotes webserver'
      become: yes
      apt:
        update_cache: yes
        pkg:
          - php
          - php-pear
          - php-curl
          - php-gd
          - php-intl
          - php-xmlrpc
          - php-mysql
          - apache2
          - python3-mysqldb
          - wget
          - zip
          - curl
          - vim
        state: present
      when: ansible_os_family == 'Debian'
    - name: 'Diretorio do webserver'
      become: yes
      file:
        path: /srv/www/express
        state: directory
        owner: "{{ app_user }}"
        mode: '0775'
    - name: 'Download e Extração do arquivo da aplicação'
      unarchive:
        src: web/web.zip
        dest: /srv/www/express
    - name: 'Substitui Ip de Conexão com o Banco'
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '172.17.177.102'
    - name: 'Criando virtual host para a pagina express.asf.com'
      template:
        src: "files/express.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
    - name: 'Controle de Diretório Virtual Host'
      template:
        src: "files/direxpress.conf"
        dest: "/etc/apache2/conf-available/direxpress.conf"
    - name: 'Entrada DNS arquivo /etc/hosts'
      template:
        src: "files/hostsweb.conf"
        dest: "/etc/hosts"
    - name: 'Habilitar Site'
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache
    - name: 'Habilitar Arquivo de configuração express'
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: Restart Apache
    - name: 'Habilitar Modulo php7'
      apache2_module:
        state: present
        name: php7.4
      notify: Reload Apache
    - name: 'Habilitar Modulo Virtual Host'
      apache2_module:
        state: present
        name: vhost_alias
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
    - name: Start Apache
      service:
        name: apache2
        state: started
